export const COMMAND_HIERARCHY: Record<string, string> = {
  "giveaways:start": "giveaway",
  "giveaways:end": "giveaway",
  "giveaways:reroll": "giveaway",

  "antinuke:modules": "antinuke",
  "antinuke:status": "antinuke",
  "antinuke:punishment": "antinuke",
  "antinuke:recovery": "antinuke",
  "antinuke:threshold_set": "antinuke",
  "antinuke:logchannel": "antinuke",
  "antinuke:whitelist": "antinuke",
  "antinuke:manage": "antinuke whitelist",

  "selfroles:button": "selfroles",
  "selfroles:dropdown": "selfroles",

  "fun:8ball": "fun",
  "fun:dice": "fun",
  "fun:coinflip": "fun",
  "fun:dih": "fun",
  "fun:choose": "fun",
  "fun:rps": "fun",
  "fun:humble": "fun",
  "fun:caption": "fun",
  "fun:base64": "fun",
  "fun:ai": "fun",
  "fun:aiclear": "fun",
  "fun:sha256": "fun",
  "fun:steal": "fun",
  "fun:translate": "fun",
  "fun:pp": "fun",
  "fun:dihr": "fun",
  "fun:tts": "fun",
  "fun:urban": "fun",
  "fun:image": "fun",
  "fun:img2gif": "fun",

  "automod:anti-spam": "automod",
  "automod:invitelinks": "automod",
  "automod:massmention": "automod",
  "automod:words": "automod",
  "automod:walloftext": "automod",
  "automod:antilink": "automod",
  "automod:emojispam": "automod",
  "automod:migrate": "automod",
  "automod:logchannel": "automod",
  "automod:unmigrate": "automod",

  "suggestions:panel": "suggestions",
  "suggestions:unblacklist": "suggestions",
  "suggestions:blacklist": "suggestions",
  "suggestions:setup": "suggestions",

  "security:anti-ping": "security",
  "security:anti-webhook_spam": "security",
  "security:punishment_set": "security",

  "tags:show": "tag",
  "tags:raw": "tag",
  "tags:create": "tag",
  "tags:edit": "tag",
  "tags:delete": "tag",
  "tags:list": "tag",
  "tags:info": "tag",
  "tags:search": "tag",
  "tags:alias": "tag",
  "tags:unalias": "tag",
  "tags:owner": "tag",
  "tags:transfer": "tag",
  "tags:lock": "tag",
  "tags:unlock": "tag",
  "tags:random": "tag",
  "tags:top": "tag",

  "roles:role": "roles",
  "roles:add": "roles",
  "roles:remove": "roles",
  "roles:list": "roles",
  "roles:info": "roles",
  "roles:create": "roles",
  "roles:delete": "roles",
  "roles:color": "roles",
  "roles:members": "roles",
  "roles:bulk": "roles",
  "roles:massadd": "roles",
  "roles:booster": "roles",
  "roles:sanitize": "roles",
  "roles:all": "roles sanitize",
  "roles:user": "roles sanitize",
  "roles:setup": "roles",
  "roles:settings": "roles",
  "roles:autorole": "roles",

  "leveling:leaderboard": "level",
  "leveling:up": "level",
  "leveling:rank": "level",
  "leveling:card": "level",
  "leveling:settings": "level",
  "leveling:add": "level",
  "leveling:remove": "level",
  "leveling:exempt": "level",

  "autopurge:interval": "autopurge",
  "autopurge:limit": "autopurge",
  "autopurge:type": "autopurge",
  "autopurge:notify": "autopurge",
  "autopurge:pause": "autopurge",
  "autopurge:resume": "autopurge",
  "autopurge:history": "autopurge",
  "autopurge:logchannel": "autopurge",
  "autopurge:enable": "autopurge",
  "autopurge:disable": "autopurge",
  "autopurge:whitelist": "autopurge",
  "autopurge:add": "autopurge whitelist",
  "autopurge:remove": "autopurge whitelist",
  "autopurge:list": "autopurge whitelist",
  "autopurge:blacklist": "autopurge",
  "autopurge:lock": "autopurge",
  "autopurge:unlock": "autopurge",
  "autopurge:status": "autopurge",

  "emojiboard:set": "emojiboard",
  "emojiboard:addemoji": "emojiboard",
  "emojiboard:removeemoji": "emojiboard",
  "emojiboard:list": "emojiboard",
  "emojiboard:channel": "emojiboard",
  "emojiboard:setchannel": "emojiboard",
  "emojiboard:removechannel": "emojiboard",
  "emojiboard:channels": "emojiboard",
  "emojiboard:threshold": "emojiboard",
  "emojiboard:config": "emojiboard",
  "emojiboard:enable": "emojiboard",
  "emojiboard:disable": "emojiboard",
  "emojiboard:lock": "emojiboard",
  "emojiboard:unlock": "emojiboard",
  "emojiboard:top": "emojiboard",
  "emojiboard:stats": "emojiboard",
  "emojiboard:whitelist": "emojiboard",
  "emojiboard:blacklist": "emojiboard",
  "emojiboard:role": "emojiboard",
  "emojiboard:user": "emojiboard",
  "emojiboard:pingrole": "emojiboard",
  "emojiboard:add": "emojiboard pingrole",
  "emojiboard:remove": "emojiboard pingrole",
  "emojiboard:clear": "emojiboard",
  "emojiboard:reset": "emojiboard",

  "triggers:list": "triggers",
  "triggers:create": "triggers",
  "triggers:strict": "triggers",
  "triggers:exact": "triggers",
  "triggers:startswith": "triggers",
  "triggers:endswith": "triggers",
  "triggers:regex": "triggers",
  "triggers:remove": "triggers",
  "triggers:clear": "triggers",
  "triggers:channel": "triggers",
  "triggers:ignore": "triggers",
  "triggers:unignore": "triggers",
  "triggers:edit": "triggers",
  "triggers:info": "triggers",
  "triggers:enable": "triggers",
  "triggers:disable": "triggers",
  "triggers:move": "triggers",
  "triggers:rename": "triggers",
  "triggers:duplicate": "triggers",
  "triggers:toggle": "triggers",
  "triggers:log": "triggers",
  "triggers:stats": "triggers",
  "triggers:search": "triggers",
  "triggers:import": "triggers",
  "triggers:export": "triggers",

  "stats:topmessages": "stats",
  "stats:topinvites": "stats",
  "stats:joinlog": "stats",
  "stats:leavelog": "stats",
  "stats:view": "stats",
  "stats:user": "stats",
  "stats:messages": "stats",
  "stats:invites": "stats",
  "stats:server": "stats",
  "stats:log": "stats",
  "stats:set": "stats log",
  "stats:clear": "stats log",

  "settings:backup": "settings",
  "settings:create": "settings backup",
  "settings:list": "settings backup",
  "settings:restore": "settings backup",
  "settings:delete": "settings backup",
  "settings:customise": "settings",
  "settings:pfp": "settings customise",
  "settings:bio": "settings customise",
  "settings:banner": "settings customise",
  "settings:name": "settings customise",

  "moderation:list": "moderation",
  "moderation:user": "moderation",
  "moderation:invites": "moderation",
  "moderation:set": "moderation",
  "moderation:clear": "moderation",
  "moderation:delete": "moderation",
  "moderation:create": "moderation",
  "moderation:add": "moderation",
  "moderation:remove": "moderation",
  "moderation:lock": "moderation",
  "moderation:unlock": "moderation",
  "moderation:edit": "moderation",
  "moderation:all": "moderation",
  "moderation:channels": "moderation",
  "moderation:voice": "moderation",
  "moderation:warn": "moderation",
  "moderation:modwarnings": "moderation",
  "moderation:warnings": "moderation",
  "moderation:modthresholds": "moderation",
  "moderation:thresholds": "moderation",
  "moderation:setwarnthreshold": "moderation",
  "moderation:ghostping": "moderation",
  "moderation:nuke": "moderation",
  "moderation:purge": "moderation",
  "moderation:bot": "moderation purge",
  "moderation:humans": "moderation purge",
  "moderation:contains": "moderation purge",
  "moderation:links": "moderation purge",
  "moderation:embeds": "moderation purge",
  "moderation:emoji": "moderation purge",
  "moderation:images": "moderation purge",
  "moderation:files": "moderation purge",
  "moderation:mentions": "moderation purge",
  "moderation:reactions": "moderation purge",
  "moderation:cleanup": "moderation purge",
  "moderation:length": "moderation purge",
  "moderation:slowmode": "moderation",
  "moderation:sticky": "moderation",
  "moderation:snipe": "moderation",
  "moderation:editsnipe": "moderation",
  "moderation:reactionsnipe": "moderation",
  "moderation:clearsnipe": "moderation",
  "moderation:text": "moderation channels create",
  "moderation:category": "moderation",
  "moderation:clone": "moderation",
  "moderation:protect": "moderation",
  "moderation:unprotect": "moderation",
  "moderation:mod": "moderation",
  "moderation:forcenick": "moderation",
  "moderation:removeforcenick": "moderation",
  "moderation:kick": "moderation",
  "moderation:hardban": "moderation",
  "moderation:softban": "moderation",
  "moderation:ban": "moderation",
  "moderation:unbanall": "moderation",
  "moderation:unban": "moderation",
  "moderation:removehardban": "moderation",
  "moderation:mute": "moderation",
  "moderation:unmute": "moderation",
  "moderation:timeout": "moderation",
  "moderation:untimeout": "moderation",
  "moderation:untimeoutall": "moderation",
  "moderation:unmuteall": "moderation",
  "moderation:lockall": "moderation",
  "moderation:unlockall": "moderation",

  "utility:ping": "utility",
  "utility:echo": "utility",
  "utility:botinfo": "utility",
  "utility:afk": "utility",
  "utility:avatar": "utility",
  "utility:device": "utility",
  "utility:changelog": "utility",
  "utility:myid": "utility",
  "utility:checkdev": "utility",
  "utility:profile": "utility",
  "utility:poll": "utility",
  "utility:reminder": "utility",
  "utility:reminders": "utility",
  "utility:server": "utility",
  "utility:info": "utility server",
  "utility:icon": "utility server",
  "utility:banner": "utility server",
  "utility:prefixes": "utility",
  "utility:add": "utility prefixes",
  "utility:remove": "utility prefixes",
  "utility:list": "utility prefixes",
  "utility:imageonly": "utility",
  "utility:bypass": "utility",
  "utility:voice": "utility",
  "utility:setup": "utility voice",
  "utility:disable": "utility voice",
  "utility:settings": "utility voice",
  "utility:sync": "utility",

  "badge:add": "badge",
  "badge:remove": "badge",
  "badge:list": "badge",
  "badge:channel": "badge",
  "badge:sync": "badge",
  "badge:customize": "badge",
  "badge:variables": "badge",

  "greet:message": "greet",
  "greet:set": "greet message",
  "greet:remove": "greet message",
  "greet:preview": "greet message",
  "greet:channel": "greet",
  "greet:add": "greet channel",
  "greet:dm": "greet",
  "greet:enable": "greet dm",
  "greet:disable": "greet dm",
  "greet:status": "greet dm",
  "greet:leave": "greet",
  "greet:message-set": "greet leave",
  "greet:message-remove": "greet leave",
  "greet:message-preview": "greet leave",
  "greet:channel-add": "greet leave",
  "greet:channel-remove": "greet leave",
  "greet:autorole": "greet",
  "greet:bots": "greet autorole",
  "greet:humans": "greet autorole",
  "greet:clear": "greet autorole",
  "greet:test": "greet",
  "greet:welcome": "greet test",
  "utility:messages": "utility",
  "utility:logs": "utility",
  "utility:qr": "utility",
  "utility:scannsfw": "utility",
  "utility:announce": "utility",
  "utility:serverinfo": "utility",
  "utility:prefix": "utility",

  "welcome:greet": "welcome",

  "fakepermissions:add": "fakepermissions",
  "fakepermissions:remove": "fakepermissions",
  "fakepermissions:clear": "fakepermissions",
  "fakepermissions:list": "fakepermissions",
  "fakepermissions:user": "fakepermissions",
  "fakepermissions:check": "fakepermissions",
  "fakepermissions:test": "fakepermissions",
  "fakepermissions:compare": "fakepermissions",
  "fakepermissions:whohas": "fakepermissions",
  "fakepermissions:copy": "fakepermissions",
  "fakepermissions:sync": "fakepermissions",
  "fakepermissions:reset": "fakepermissions",
  "fakepermissions:permissions": "fakepermissions",
  "fakepermissions:user_add": "fakepermissions user",
  "fakepermissions:user_remove": "fakepermissions user",
  "fakepermissions:user_clear": "fakepermissions user",
  "fakepermissions:user_list": "fakepermissions user",
  "fakepermissions:permissions_view": "fakepermissions permissions",

  "admin:cleanup": "admin",
  "admin:cleanup_roles": "admin cleanup",
  "admin:cleanup_channels": "admin cleanup",
  "admin:cleanup_bots": "admin cleanup",
  "admin:cleanup_duplicates": "admin cleanup",
  "admin:announce": "admin",
  "admin:notes": "admin",
  "admin:notes_add": "admin notes",
  "admin:notes_remove": "admin notes",
  "admin:notes_view": "admin notes",
  "admin:recent": "admin",
  "admin:recent_bans": "admin recent",
  "admin:recent_kicks": "admin recent",
  "admin:viewwarnings": "admin",
  "admin:history": "admin",
  "admin:admin_history": "admin"
};

export function getCommandParent(category: string, commandName: string): string | null {
  const key = `${category}:${commandName}`;
  return COMMAND_HIERARCHY[key] || null;
}